name: hypaper
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.9.3
  theme_provider: ^0.5.0
  sembast: ^3.2.0+1
  get_it: ^7.2.0
  path_provider: ^2.0.11
  path: ^1.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/app/

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/logo.png"
